### ISSUE TITLE
idSelector falsely reports attribute selectors

### ISSUE THREAD

**Issue by bartveneman** [t32k/stylestats#124]
The analyzer will report `[href="#foo"]` as an id-selector, which it isn't. Maybe the test should be appended with these selectors, which would yield **2** id-selectors:

```css
#foo,
.foo #bar,
[id='baz'],
[href='#crux'],
[href=#foo] {
	content: '#foo';
}
```
