### ISSUE TITLE
universalSelector falsely reports attribute selectors

### ISSUE THREAD

**Issue by bartveneman** [t32k/stylestats#125]
The analyzer will report `[class*="foo"]` as a universal selector, which it isn't. Maybe the test should be appended with these selectors, which would yield **3** universal selectors:
```css
*,
.foo *,
.foo * .bar,
[class*='foo'] {
	content: '*';
}
```
