### ISSUE TITLE
TypeError: Cannot call method '***' of undefined

### ISSUE THREAD

**Issue by t32k** [t32k/stylestats#3]
``` css
.bubble {
    position: relative;
    display: block;
    padding: 10px 15px;
    /*min-width: 170px;*/
    background-color: #f2f2f2;
    text-align: left;
}
```
